const sidebars = {
  docSidebar: [
    "index",
    {
      type: "category",
      label: "Introduction",
      link: {
        type: "generated-index",
      },
      //items: [{ type: "autogenerated", dirName: "introduction" }],
      items: [
        "introduction/getting-started",
        "introduction/introduction-to-0x",
        "introduction/guides",
        "introduction/community",
        "introduction/0x-cheat-sheet",
        "developer-resources/faqs-and-troubleshooting",
      ],
      collapsed: false,
    },
    {
      type: "category",
      label: "Swap API",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "0x-swap-api" }],
      // collapsible: false,
      // collapsed: false,
    },
    {
      type: "category",
      label: "Tx Relay API",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "tx-relay-api" }],
      // collapsible: false,
    },
    {
      type: "category",
      label: "Orderbook API",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "0x-orderbook-api" }],
      // collapsible: false,
    },
    {
      type: "category",
      label: "Limit Order (Advanced Traders)",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "0x-limit-orders" }],
      // collapsible: false,
    },
    {
      type: "category",
      label: "Liquidity Providers",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "liquidity-providers" }],
      // collapsible: false,
    },
    {
      type: "category",
      label: "Developer Resources",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "link",
          label: "System status",
          href: "https://status.0x.org/",
        },
        "developer-resources/glossary",
        "developer-resources/faqs-and-troubleshooting",
        "developer-resources/contract-addresses",
        "developer-resources/how-to-get-0x-and-matcha-data",
        "developer-resources/audits",
        "developer-resources/bounties",
        "developer-resources/0x-legal-guide",
        "developer-resources/white-paper",
        "developer-resources/0x-explorer-tag-guide",
      ],
      // collapsible: true,
      // collapsed: false,
    },
    {
      type: "category",
      label: "Contact Us",
      link: {
        type: "generated-index",
      },
      items: [
        {
          type: "link",
          label: "Contact Support",
          href: "https://help.0x.org/en/articles/8230055-how-to-get-support-from-the-0x-team",
        },
        {
          type: "link",
          label: "Help Center",
          href: "https://help.0x.org/en/",
        },
        {
          type: "link",
          label: "Submit a Feature Request",
          href: "https://help.0x.org/en/articles/8410844-how-to-submit-a-0x-feature-request",
        },
        {
          type: "link",
          label: "Contact Sales",
          href: "https://0x.org/contact",
        },
      ],
      // collapsible: true,
      // collapsed: false,
    },
  ],
};

module.exports = sidebars;
